SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` DROP FOREIGN KEY `', CONSTRAINT_NAME, '`;') AS drop_statement
FROM information_schema.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_SCHEMA = DATABASE()
  AND (TABLE_NAME, COLUMN_NAME) IN (
    ('departements', 'region_id'),
    ('villes', 'departement_id'),
    ('communes', 'ville_id'),
    ('communes', 'divisionregionaleaej_id'),
    ('sous_secteurs_activites', 'secteur_activite_id'),
    ('services', 'direction_id'),
    ('fonctions', 'service_id'),
    ('entreprises', 'type_entreprise_id'),
    ('entreprises', 'region_id'),
    ('entreprises', 'commune_id'),
    ('organisme_financements', 'type'),
    ('organisme_financements', 'region_id'),
    ('personnels', 'fonction_id'),
    ('lieux_habitation', 'ville_id'),
    ('projets', 'secteur_id'),
    ('zones_intervention', 'projet_id'),
    ('zones_intervention', 'departement_id'),
    ('dispositifs', 'projet_id'),
    ('promoteurs', 'sexe_id'),
    ('promoteurs', 'lieuhabitation_id'),
    ('promoteurs', 'agenceregionale_id'),
    ('promoteurs', 'typepieceidentite_id'),
    ('promoteurs', 'niveauetude_id'),
    ('promoteurs', 'paysnationalite_id'),
    ('promoteurs', 'secteuractivite_id'),
    ('promoteurs', 'soussecteuractivite_id'),
    ('promoteurs', 'situationmatrimoniale_id'),
    ('promoteurs', 'typesituationhandicap_id'),
    ('micro_projets', 'organisme_id'),
    ('micro_projets', 'guichet_id'),
    ('micro_projets', 'secteur_id'),
    ('micro_projets', 'commune_id'),
    ('micro_projets', 'agence_id'),
    ('compte_financements', 'organisme_id'),
    ('decaissements', 'agence_id'),
    ('embauches', 'entreprise_id')
);